spring:
  devtools:
    livereload:
      enabled: false

  datasource:
    url: jdbc:mariadb://192.168.123.100:3307/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: 1234

  jpa:
    # 테이블 자동생성
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    # log - sql의 내용을 보여줌
    show-sql: true

  mail:
    host: smtp.gmail.com
    # default
    port: 587
    username: syer1122@gmail.com
    password: bebqgbnmupsblfwl
    properties:
      mail:
        smtp:
          starttls:
            enable: true







